### ISSUE TITLE
VTT Parsing adding \N as newline separator

### ISSUE THREAD

**Issue by rteabeault** [adracea/rsubs-lib#18]
I create an SRT from a VTT string.

```
let sub: vtt::SRTFile = Subtitle::from_str(vtt_subs).unwrap().into();
```

Then all the newlines `\n` have been replaced with `\N`. I think that is happening here?

https://github.com/adracea/rsubs-lib/blob/2b34070baea0542f322dceacd9d5432f867c77dd/src/vtt.rs#L447C1-L448C1

Is this intended?

**Comment by rteabeault** [comment]
Looks like the `\N` is replaced in the `fmt` function but if you just try to iterate over the subtitles and get the `line_text` it is present.

**Comment by adracea** [comment]
Hey, @rteabeault ,
The `\N` workaround is there because unlike .srt and .ssa, webvtt actually uses double line breaks to determine a new line which enables multiple lines with single line breaks. I'll try to see if I can provide a more elegant workaround.
