### ISSUE TITLE
VTT to ASS does not copy styles

### ISSUE THREAD

**Issue by felri** [adracea/rsubs-lib#41]
Hello, great lib first of all.

I'm trying to parse a VTT sub to ASS, it seems to work great but the styles from VTT is not being parsed to ASS:

```
WEBVTT

STYLE
::cue { color: #fccb00; font-weight: bold; background: #004dcf; font-family: sans-serif; text-shadow: 2px 2px 4px black; font-size: 40px; }


00:00:00.259 --> 00:00:00.899
how 

00:00:00.899 --> 00:00:01.200
to 
```

```
[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,Strikeout,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: Default,Trebuchet MS,20,&H00FFFFFF,&H00000000,&H00000000,&H00000000,-1,0,0,0,120,120,0,0,1,1,1,2,0000,0000,0030,0

[Events]
Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
Dialogue: 0,0:00:00.89,0:00:01.20,Default,,0000,0000,0000,,to 
Dialogue: 0,0:00:01.20,0:00:01.53,Default,,0000,0000,0000,,strengthen 
```

Is this something not implemented yet? And is the Line param that defines the height of the subtitle supported?

**Comment by adracea** [comment]
Hey,

Cheers! I'll try find some time this week and take a look.
If I remember correctly, off the top of my head, one of the issues I had
with this was that there is a case where ASS has too much customization and
the styles have to be applied to each line in particular as well as wildly
different implementations of their interpreting, where players were
rendering them completely off(vlc was one of them if I remember
correctly?).
I think quite a few niceties were oddly finicky depending on player and I
had to resort to creating a functional default and giving the option for
creating and applying styles manually, but it's not automatically handled.

**Comment by felri** [comment]
I think the problem in my case is [here](https://github.com/adracea/rsubs-lib/blob/00a97c120dd973919d54b29b8ada6fb7feb1df10/src/vtt.rs#L488), basically I need to change the indentation of the STYLE block inside my vtt file

```diff
-STYLE
-::cue { color: #fccb00; font-weight: bold; background: #004dcf; font-family: sans-serif; text-shadow: 2px 2px 4px black; font-size: 40px; }
+STYLE
+::cue {
+color: #fccb00;
+font-weight: bold;
+background: #004dcf;
+font-family: sans-serif;
+text-shadow: 2px 2px 4px black;
+font-size: 40px;
}
