### ISSUE TITLE
Return Error instead of panic

### ISSUE THREAD

**Issue by rbozan** [adracea/rsubs-lib#43]
https://github.com/adracea/rsubs-lib/blob/00a97c120dd973919d54b29b8ada6fb7feb1df10/src/vtt.rs#L484

Why can't you return an Error here instead of panicking?

**Comment by adracea** [comment]
I think the idea behind this panic was initially to just completely stop if
the file is broken.
I'll have to change this as I see quite a few issues coming out of this.
Thanks for bringing it up!

**Comment by rbozan** [comment]
Thanks for the crate by the way.
